version: '3'
services:   
  core:
    container_name: core
    image: ricardojob/core
    build: 
      context: ../
      dockerfile: ./docker/core/Dockerfile
    ports: 
     - "8080:8080"
    depends_on: 
     - banco
    links: 
     - "banco:host-banco"
  web:
    container_name: web
    image: ricardojob/web
    build: 
      context: ../
      dockerfile: ./docker/web/Dockerfile
    ports: 
     - "8081:8080"
    depends_on: 
     - core
    links: 
     - "core:host-core"  
#  jse:
#    container_name: jse
#    image: ricardojob/jse
#    build: 
#      context: ../
#      dockerfile: ./docker/jse/Dockerfile
#    depends_on: 
#     - core
#    links: 
#     - "core:host-core"  
  banco:
    container_name: banco
    image: ricardojob/banco
    build: ./postgres
    ports: 
    - "5433:5432"
#    volumes:
#      - "dbdata:/var/lib/postgresql/data"