version: '3'
services:   
  banco:
    container_name: banco
    image: ricardojob/banco
    build: ./postgres
    ports: 
    - "5433:5432"
#    volumes:
#      - "dbdata:/var/lib/postgresql/data"
  app:
    container_name: app
    image: ricardojob/app
    build: 
      context: ../
      dockerfile: ./docker/app/Dockerfile
    ports: 
     - "8080:8080"
    depends_on: 
     - banco
    links: 
     - "banco:host-banco"  